### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [hogsy/hosae#10]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this reimplementation in the README. Even early screenshots are fine!

**Comment by hogsy** [comment]
Done!

**Comment by clort81** [comment]
Are those screenshots with upscaled or original textures?  they look very nice.

**Comment by hogsy** [comment]
> Are those screenshots with upscaled or original textures?  they look very nice.

The originals.
