### ISSUE TITLE
Some Anachronox Infos and Tools 

### ISSUE THREAD

**Issue by clort81** [hogsy/hosae#18]
Changes from previous idtech engine:
-Seamless hierarchical/skeletal models
-colored directional model vertex-lighting
-an improved animation system
-increased model vertex coordinate resolution
-dynamic model-geometry levels of detail
-phoneme-matched vertex mouth/lip synching
-complete facial deformation for extreme expressiveness
-32-bit textures
-a robust particle system
-a flexible beam system
-lense flares
-ambient & volumetric fog
-procedural textures
-dynamic texture level of detail (for low-end video cards)
-true-type font support
-DirectMusic support (with seamless theme transitions)
-MP3 support
-a robust sound system including support for 3D sound (DS3D, EAX, A3D)
-improved radiosity algorithms.
-Hundreds of NPC's
-heavy duty control for modmakers
-parabolic environment mapping
-mini-games mixed in with standard play
-most QuakeII engine hard limits such as the max number of entities, the max number of entity vertices, map size andcomplexity, size of light maps, etc, etc doubled or quadruple

Anachrodox v1.2/Tools (6.6 MB): The remaining Anachronox editing tools, such as ION Radiant and dparse. Also included are a gigantic assortment of documentation and tutorials and maps.
 
[anachrodox1_2.zip](https://github.com/hogsy/hosae/files/7698285/anachrodox1_2.zip)

[Info on maps and map editing (steamcommunity)](https://steamcommunity.com/sharedfiles/filedetails/?id=924639902)

**Comment by hogsy** [comment]
>  -true-type font support

Are you sure? I'm not sure what the game would be using this for, as it looks to me like it just uses textures for fonts everywhere. If you have an example that'd be great.

>  -a robust sound system including support for 3D sound (DS3D, EAX, A3D)

We'll just be using OpenAL instead.

>  -Seamless hierarchical/skeletal models

Not really. All the models still use per-vertex animation. I think there's an attachment similar to what Daikatana has, so vertices can be marked and other entities can essentially follow those vertices - not currently sure how transforms are handled as I've not looked into it too deeply at this stage.

**Comment by hogsy** [comment]
I've split some of these into their own tickets where it made sense to do so. Will close this one now.
